<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>LukisHardModMenu</AssemblyName>
    <RootNamespace>LukisHardModMenu</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- BepInEx -->
    <Reference Include="BepInEx">
      <HintPath>..\..\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>

    <!-- Unity -->
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Gorilla Tag_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.XRModule">
      <HintPath>..\..\Gorilla Tag_Data\Managed\UnityEngine.XRModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Menu\LukisHardModMenu.cs" />
  </ItemGroup>

</Project>
